/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type CaseStudyReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'case-study'
}

export type CaseStudyOrder = {
  _id: string
  _type: 'case-study-order'
  _createdAt: string
  _updatedAt: string
  _rev: string
  caseStudies?: Array<
    {
      _key: string
    } & CaseStudyReference
  >
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type CaseStudy = {
  _id: string
  _type: 'case-study'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description: string
  liveUrl?: string
  slug: Slug
  mainImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: string
    _type: 'image'
  }
  platform: 'Astro + Sanity' | 'Astro' | 'Webflow' | 'Shopify' | 'Wix' | 'WordPress' | 'HubSpot' | 'Squarespace'
  workedWith: 'for-agency' | 'with-agency' | 'direct'
  services?: Array<string>
  publishedAt: string
  body: BlockContent
}

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h2' | 'h3' | 'h4' | 'h5' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt: string
      caption?: string
      _type: 'image'
      _key: string
    }
  | ({
      _key: string
    } & Code)
>

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type Code = {
  _type: 'code'
  language?: string
  filename?: string
  code?: string
  highlightedLines?: Array<number>
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | CaseStudyReference
  | CaseStudyOrder
  | SanityImageAssetReference
  | CaseStudy
  | BlockContent
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Code
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: src/sanity/lib/queries.ts
// Variable: CASE_STUDIES_QUERY
// Query: {  "caseStudies": *[_type == "case-study"] | order(publishedAt desc) {    _id,    title,    slug,    mainImage,    publishedAt,    description,    platform,    workedWith,  },  "order": *[_id == "case-study-order"][0].caseStudies[]._ref,}
export type CASE_STUDIES_QUERY_RESULT = {
  caseStudies: Array<{
    _id: string
    title: string
    slug: Slug
    mainImage: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt: string
      _type: 'image'
    }
    publishedAt: string
    description: string
    platform: 'Astro + Sanity' | 'Astro' | 'HubSpot' | 'Shopify' | 'Squarespace' | 'Webflow' | 'Wix' | 'WordPress'
    workedWith: 'direct' | 'for-agency' | 'with-agency'
  }>
  order: Array<string> | null
}

// Source: src/sanity/lib/queries.ts
// Variable: CASE_STUDY_PAGES_QUERY
// Query: *[_type == "case-study" && defined(slug.current)] {  title,  slug,  mainImage,  publishedAt,  description,  services,  body,  liveUrl,  "estimatedReadingTime": round(length(pt::text(body)) / 5 / 180)}
export type CASE_STUDY_PAGES_QUERY_RESULT = Array<{
  title: string
  slug: Slug
  mainImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: string
    _type: 'image'
  }
  publishedAt: string
  description: string
  services: Array<string> | null
  body: BlockContent
  liveUrl: string | null
  estimatedReadingTime: number
}>

// Query TypeMap
declare global {
  interface SanityQueries {
    '{\n  "caseStudies": *[_type == "case-study"] | order(publishedAt desc) {\n    _id,\n    title,\n    slug,\n    mainImage,\n    publishedAt,\n    description,\n    platform,\n    workedWith,\n  },\n  "order": *[_id == "case-study-order"][0].caseStudies[]._ref,\n}': CASE_STUDIES_QUERY_RESULT
    '*[_type == "case-study" && defined(slug.current)] {\n  title,\n  slug,\n  mainImage,\n  publishedAt,\n  description,\n  services,\n  body,\n  liveUrl,\n  "estimatedReadingTime": round(length(pt::text(body)) / 5 / 180)\n}': CASE_STUDY_PAGES_QUERY_RESULT
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module '@sanity/client' {
  interface SanityQueries extends globalThis.SanityQueries {}
}
